parameters:
    wd_image_manager.class: WernerDweight\ImageManagerBundle\Utils\ImageManagerUtility

services:
    wd_image_manager:
        class: %wd_image_manager.class%
        calls:
        - [setContainer, ['@service_container']]
