services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\ImageManagerBundle\Service\ImageManagerUtility:
        calls:
            - [setContainer, ['@service_container']]
